let greeting_Time = "Hi, I'm Souhardya!";
let numder = 32;
alert(greeting_Time);
alert(numder);
alert(greeting_Time);
greeting_Time = "Hi, I'm really Souhardya!";
alert(greeting_Time);
alert(`My age is ${numder}`);
numder = 34;
alert(numder);